/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import IDSSecureStorage from './src/utils/memory';

/*const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  // aws_user_pools_id: 'us-east-1_3bYkTtXLm',
  //aws_user_pools_id : 'us-east-1_XBRYP2tEi',
  //aws_user_pools_web_client_id: '7em56erckqqp7rk1ivr9siv7n5',
  //aws_user_pools_web_client_id: '185m64qoqhl03e5ob40c9v9dvv',

  //AndresInfo
  //aws_user_pools_id: 'us-east-1_PjaTCdOjM',
  // aws_user_pools_web_client_id: '4io87i7n9pjhn6h4118b5kk8g4',

  //OldInfo
  //aws_user_pools_id: 'us-east-1_3bYkTtXLm',
  //aws_user_pools_web_client_id: '7em56erckqqp7rk1ivr9siv7n5',

  //Prasann Info
  aws_user_pools_id: 'us-east-1_XBRYP2tEi',
  aws_user_pools_web_client_id: '185m64qoqhl03e5ob40c9v9dvv',

  oauth: {
    //oldDomain
    // domain: 'idsmobileapp-dev.auth.us-east-1.amazoncognito.com',
    //Prasann domain
    domain: 'idscs-development.auth.us-east-1.amazoncognito.com',
    //andreesDomain
    // domain: 'bccmobile.auth.us-east-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
      // "ttna_auth/contractor"
    ],
    redirectSignIn: 'idsmobileapp://',
    redirectSignOut: 'idsmobileapp://',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  API: {
    endpoints: [
      {
        name: 'ttnacloudplatform-api',
        endpoint: 'https://api.boschttna.com',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-default',
        endpoint:
          'https://sq4of1j94l.execute-api.us-east-1.amazonaws.com/default',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-test',
        //HC Environment
        //tkhhujg681 IDS2.1 https://tkhhujg681.execute-api.us-east-1.amazonaws.com/development
        //f9wv5giwb3 IDS3.0  https://f9wv5giwb3.execute-api.us-east-1.amazonaws.com/testing_evn
        //9hiwm1jm25 BCC
    

        endpoint: 'https://sq4of1j94l.execute-api.us-east-1.amazonaws.com/test',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-hc',
        //ids2.1 api gateway
        //endpoint: 'https://api.dev.boschttna.com',
        endpoint: 'https://tkhhujg681.execute-api.us-east-1.amazonaws.com/development',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-hc30',
        //endpoint: 'https://api.dev.boschttna.com',
        endpoint: 'https://f9wv5giwb3.execute-api.us-east-1.amazonaws.com/testing_evn',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-hcBCC',
        endpoint: 'https://9hiwm1jm25.execute-api.us-east-1.amazonaws.com/development/device/add',
        region: 'us-east-1',
      },
    ],
  },
  Auth: {
    storage: IDSSecureStorage,
  },
};*/

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_QpSmPYmJW',
  aws_user_pools_web_client_id: '6vo6t7ek82of7m9s0tuvuq0ige',
  oauth: {
    domain: 'idscs-testing.auth.us-east-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
      // "ttna_auth/contractor"
    ],
    redirectSignIn: 'idsmobileapp://',
    redirectSignOut: 'idsmobileapp://',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  API: {
    endpoints: [
      {
        name: 'ttnacloudplatform-api',
        endpoint: 'https://api.boschttna.com',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-default',
        endpoint:
          'https://sq4of1j94l.execute-api.us-east-1.amazonaws.com/default',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-test',
        endpoint: 'https://sq4of1j94l.execute-api.us-east-1.amazonaws.com/test',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-hcBCC',
        endpoint:
          'https://9hiwm1jm25.execute-api.us-east-1.amazonaws.com/development',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-2.1',
        endpoint:
          //'https://tkhhujg681.execute-api.us-east-1.amazonaws.com/development',
          'https://93wcx0em15.execute-api.us-east-1.amazonaws.com/dev',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-3.0',
        endpoint:
          'https://f9wv5giwb3.execute-api.us-east-1.amazonaws.com/development',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-testing-api',
        endpoint:
          'https://ozjffo9z7j.execute-api.us-east-1.amazonaws.com/testing',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-pr-dev',
        endpoint:
          //'https://64dwiag3dk.execute-api.us-east-1.amazonaws.com/production/',
          'https://srjwtj51xc.execute-api.us-east-1.amazonaws.com/dev',
        region: 'us-east-1',
      },
      {
        name: 'ttnacloudplatform-api-pr-test',
        endpoint:
          'https://fsd7ngxfz4.execute-api.us-east-1.amazonaws.com/testing',
        region: 'us-east-1',
      },
    ],
  },
  Auth: {
    storage: IDSSecureStorage,
  },
};
export default awsmobile;
